import type { Expert } from "../types/expert";

export const EXPERTS: Expert[] = [
  {
    id: "e1",
    name: "Nguyễn Minh Anh",
    degreePrefix: "TS.",
    title: "Chuyên gia Tâm lý lâm sàng",
    specialty: "Tâm lý lâm sàng",
    gender: "Nữ",
    languages: ["Tiếng Việt", "English"],
    rating: 4.9,
    reviewsCount: 127,
    pricePerSessionVnd: 300_000,
    verified: true,
    avatarUrl: "https://placehold.co/1200x800/png?text=Expert+1",
  },
  {
    id: "e2",
    name: "Trần Thu Hà",
    degreePrefix: "ThS.",
    title: "Chuyên gia Tư vấn hôn nhân & gia đình",
    specialty: "Hôn nhân & gia đình",
    gender: "Nữ",
    languages: ["Tiếng Việt"],
    rating: 4.7,
    reviewsCount: 95,
    pricePerSessionVnd: 250_000,
    verified: true,
    avatarUrl: "https://placehold.co/1200x800/png?text=Expert+2",
  },
  {
    id: "e3",
    name: "Lê Hoàng Nam",
    degreePrefix: "BS.",
    title: "Bác sĩ Tâm thần",
    specialty: "Tâm thần",
    gender: "Nam",
    languages: ["Tiếng Việt", "English"],
    rating: 4.8,
    reviewsCount: 96,
    pricePerSessionVnd: 400_000,
    verified: true,
    avatarUrl: "https://placehold.co/1200x800/png?text=Expert+3",
  },
  {
    id: "e4",
    name: "Phạm Quỳnh Mai",
    degreePrefix: "TS.",
    title: "Tư vấn Trầm cảm & Lo âu",
    specialty: "Trầm cảm & Lo âu",
    gender: "Nữ",
    languages: ["Tiếng Việt"],
    rating: 5.0,
    reviewsCount: 34,
    pricePerSessionVnd: 275_000,
    verified: true,
    avatarUrl: "https://placehold.co/1200x800/png?text=Expert+4",
  },
  {
    id: "e5",
    name: "Vũ Lan Anh",
    degreePrefix: "ThS.",
    title: "Tư vấn Stress & Burnout",
    specialty: "Stress & Burnout",
    gender: "Nữ",
    languages: ["Tiếng Việt", "English"],
    rating: 4.9,
    reviewsCount: 65,
    pricePerSessionVnd: 250_000,
    verified: true,
    avatarUrl: "https://placehold.co/1200x800/png?text=Expert+5",
  },
  {
    id: "e6",
    name: "Đặng Văn Tuấn",
    degreePrefix: "BS.",
    title: "Tâm lý Trẻ em & Thanh thiếu niên",
    specialty: "Trẻ em & Thanh thiếu niên",
    gender: "Nam",
    languages: ["Tiếng Việt"],
    rating: 4.7,
    reviewsCount: 27,
    pricePerSessionVnd: 300_000,
    verified: true,
    avatarUrl: "https://placehold.co/1200x800/png?text=Expert+6",
  },
];
